import { Preset } from './types';

export const presetDatabase: Record<string, Preset> = {
  "Cu(II)-tetraammine [Cu(NH3)4]2+ (D4h)": {
    metal: "Copper (Cu2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, elongated octahedral (D4h)",
    A_par: { "Cu-63": 200, "Cu-65": 214 },
    A_perp: { "Cu-63": 25, "Cu-65": 27 },
    ligands: [{ isotope: "N-14", n: 4, A_par: 15.0, A_perp: 15.0 }],
    coordinatedLigands: [{ ligand: "NH₃ (ammonia)", count: 4 }],
    distant_nuclei: [["H-1 (Protium)", 12, 8.0, 5.0]],
  },
  "Cu(II)-water [Cu(H2O)6]2+ (D4h)": {
    metal: "Copper (Cu2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, elongated octahedral (D4h)",
    A_par: { "Cu-63": 140, "Cu-65": 150 },
    A_perp: { "Cu-63": 20, "Cu-65": 21 },
    ligands: [],
    coordinatedLigands: [{ ligand: "H₂O (water)", count: 6 }],
    distant_nuclei: [["H-1 (Protium)", 12, 8.0, 5.0]],
  },
  "Mn(II)-water [Mn(H2O)6]2+ (Oh)": {
    metal: "Manganese (Mn2+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Mn-55": 90 },
    A_perp: { "Mn-55": 90 },
    ligands: [],
    coordinatedLigands: [{ ligand: "H₂O (water)", count: 6 }],
    distant_nuclei: [["H-1 (Protium)", 12, 8.0, 5.0]],
    D_zfs: 200,
  },
  "VO(II)-water [VO(H2O)5]2+ (C4v)": {
    metal: "Vanadium (V4+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, square pyramidal (C4v)",
    A_par: { "V-51": 500 },
    A_perp: { "V-51": 170 },
    ligands: [],
    coordinatedLigands: [{ ligand: "H₂O (water)", count: 5 }],
    distant_nuclei: [["H-1 (Protium)", 10, 8.0, 5.0]],
  },
  "Cu(II)-acac2 [Cu(acac)2] (D2h)": {
    metal: "Copper (Cu2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, elongated octahedral (D4h)",
    A_par: { "Cu-63": 160, "Cu-65": 171 },
    A_perp: { "Cu-63": 25, "Cu-65": 27 },
    ligands: [],
    coordinatedLigands: [{ ligand: "acac (acetylacetonate)", count: 2 }],
    distant_nuclei: [["H-1 (Protium)", 6, 8.0, 5.0]],
  },
  "Cu(II)-en2 [Cu(en)2]2+ (D4h)": {
    metal: "Copper (Cu2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, elongated octahedral (D4h)",
    A_par: { "Cu-63": 190, "Cu-65": 203 },
    A_perp: { "Cu-63": 30, "Cu-65": 32 },
    ligands: [{ isotope: "N-14", n: 4, A_par: 25.0, A_perp: 20.0 }],
    coordinatedLigands: [{ ligand: "en (ethylenediamine)", count: 2 }],
    distant_nuclei: [["H-1 (Protium)", 8, 10.0, 7.0]],
  },
  "Cu(II)-bipy2 [Cu(bipy)2]2+ (D2)": {
    metal: "Copper (Cu2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, elongated octahedral (D4h)",
    A_par: { "Cu-63": 170, "Cu-65": 182 },
    A_perp: { "Cu-63": 25, "Cu-65": 27 },
    ligands: [{ isotope: "N-14", n: 4, A_par: 15.0, A_perp: 12.0 }],
    coordinatedLigands: [{ ligand: "bipy (bipyridine)", count: 2 }],
    distant_nuclei: [["H-1 (Protium)", 16, 5.0, 3.5]],
  },
  "VO(II)-acac2 [VO(acac)2] (C4v)": {
    metal: "Vanadium (V4+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, square pyramidal (C4v)",
    A_par: { "V-51": 500 },
    A_perp: { "V-51": 170 },
    ligands: [],
    coordinatedLigands: [{ ligand: "acac (acetylacetonate)", count: 2 }],
    distant_nuclei: [["H-1 (Protium)", 6, 7.0, 4.5]],
  },
  "Cr(III)-acac3 [Cr(acac)3] (D3)": {
    metal: "Chromium (Cr3+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Cr-53": 20 },
    A_perp: { "Cr-53": 20 },
    ligands: [],
    coordinatedLigands: [{ ligand: "acac (acetylacetonate)", count: 3 }],
    distant_nuclei: [["H-1 (Protium)", 9, 5.0, 3.5]],
    D_zfs: 400,
  },
  "Au(II)-chloride [AuCl4]2- (D4h)": {
    metal: "Gold (Au2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, square planar (D4h)",
    A_par: { "Au-197": 60 },
    A_perp: { "Au-197": 25 },
    ligands: [{ isotope: "Cl-35", n: 4, A_par: 12.0, A_perp: 8.0 }],
    coordinatedLigands: [{ ligand: "Cl⁻ (chloride)", count: 4 }],
  },
  "Au(II)-doped K2PtCl6 (Oh)": {
    metal: "Gold (Au2+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Au-197": 35 },
    A_perp: { "Au-197": 35 },
    ligands: [],
    coordinatedLigands: [{ ligand: "Cl⁻ (chloride)", count: 6 }],
  },
  "Ag(II)-doped NaCl (Oh)": {
    metal: "Silver (Ag2+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Ag-107": 40, "Ag-109": 46 },
    A_perp: { "Ag-107": 40, "Ag-109": 46 },
    ligands: [],
    coordinatedLigands: [{ ligand: "Cl⁻ (chloride)", count: 6 }],
  },
  "Ag(II)-water [Ag(H2O)6]2+ (D4h)": {
    metal: "Silver (Ag2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, elongated octahedral (D4h)",
    A_par: { "Ag-107": 45, "Ag-109": 52 },
    A_perp: { "Ag-107": 12, "Ag-109": 14 },
    ligands: [{ isotope: "O-17", n: 6, A_par: 8.0, A_perp: 5.0 }],
    coordinatedLigands: [{ ligand: "H₂O (water)", count: 6 }],
    distant_nuclei: [["H-1 (Protium)", 12, 8.0, 5.0]],
  },
  "Pt(III)-chloride [PtCl6]3- (Oh)": {
    metal: "Platinum (Pt3+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Pt-195": 80 },
    A_perp: { "Pt-195": 80 },
    ligands: [],
    coordinatedLigands: [{ ligand: "Cl⁻ (chloride)", count: 6 }],
  },
  "Ni(I)-cyanide [Ni(CN)4]3- (D4h)": {
    metal: "Nickel (Ni+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, square planar (D4h)",
    A_par: { "Ni-61": 20 },
    A_perp: { "Ni-61": 10 },
    ligands: [],
    coordinatedLigands: [{ ligand: "CN⁻ (cyanide)", count: 4 }],
    lambdaMod: 700,
    Dc: 15000,
    Dpar: 22000,
    Dperp: 26000,
    Dx: 26000,
    Dy: 26000,
    Dz: 22000,
  },
  "Fe(III)-porphyrinCl [Fe(TPP)Cl] (C4v)": {
    metal: "Iron (Fe3+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_z2, square pyramidal (C4v)",
    A_par: { "Fe-57": 22 },
    A_perp: { "Fe-57": 22 },
    ligands: [{ isotope: "N-14", n: 4, A_par: 15.0, A_perp: 12.0 }],
    coordinatedLigands: [{ ligand: "porphyrin (TPP)", count: 1 }, { ligand: "Cl⁻ (chloride)", count: 1 }],
    distant_nuclei: [["H-1 (Protium)", 8, 5.0, 3.5]],
    D_zfs: 600,
  },
  "Co(II)-water [Co(H2O)6]2+ (Oh)": {
    metal: "Cobalt (Co2+, high-spin)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_z2, tetragonally compressed octahedral (D4h)",
    A_par: { "Co-59": 100 },
    A_perp: { "Co-59": 100 },
    ligands: [],
    coordinatedLigands: [{ ligand: "H₂O (water)", count: 6 }],
    distant_nuclei: [["H-1 (Protium)", 12, 8.0, 5.0]],
    D_zfs: 500,
  },
  "Mn(II)-EDTA [Mn(EDTA)]2-": {
    metal: "Manganese (Mn2+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Mn-55": 90 },
    A_perp: { "Mn-55": 90 },
    ligands: [{ isotope: "N-14", n: 2, A_par: 20.0, A_perp: 15.0 }],
    coordinatedLigands: [{ ligand: "EDTA", count: 1 }],
    D_zfs: 250,
  },
  "Co(II)-acac2 [Co(acac)2] (D2d)": {
    metal: "Cobalt (Co2+, high-spin)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_z2, tetrahedral (D2d distortion)",
    A_par: { "Co-59": 110 },
    A_perp: { "Co-59": 80 },
    ligands: [],
    coordinatedLigands: [{ ligand: "acac (acetylacetonate)", count: 2 }],
    distant_nuclei: [["H-1 (Protium)", 6, 7.0, 4.5]],
    D_zfs: 800,
  },
  "Cr(III)-water [Cr(H2O)6]3+ (Oh)": {
    metal: "Chromium (Cr3+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Cr-53": 18 },
    A_perp: { "Cr-53": 18 },
    ligands: [],
    coordinatedLigands: [{ ligand: "H₂O (water)", count: 6 }],
    distant_nuclei: [["H-1 (Protium)", 12, 5.0, 3.5]],
    D_zfs: 50,
  },
  "Fe(III)-cyanide [Fe(CN)6]3- (Oh)": {
    metal: "Iron (Fe3+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Fe-57": 15 },
    A_perp: { "Fe-57": 15 },
    ligands: [],
    coordinatedLigands: [{ ligand: "CN⁻ (cyanide)", count: 6 }],
    D_zfs: 0,
  },
  "Co(II)-ammine [Co(NH3)6]2+ (Oh, HS)": {
    metal: "Cobalt (Co2+, high-spin)",
    symmetry: "Cubic / isotropic",
    A_par: { "Co-59": 90 },
    A_perp: { "Co-59": 90 },
    ligands: [{ isotope: "N-14", n: 6, A_par: 12.0, A_perp: 12.0 }],
    coordinatedLigands: [{ ligand: "NH₃ (ammonia)", count: 6 }],
    D_zfs: 200,
  },
  "Mn(II)-doped MgO (Oh)": {
    metal: "Manganese (Mn2+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Mn-55": 82 },
    A_perp: { "Mn-55": 82 },
    ligands: [],
    D_zfs: 10,
  },
  "Cu(II)-acac2 in CHCl3 (rhombic)": {
    metal: "Copper (Cu2+)",
    symmetry: "Rhombic",
    manualG: true,
    gx: 2.045,
    gy: 2.055,
    gz: 2.290,
    A_par: { "Cu-63": 160, "Cu-65": 171 },
    A_perp: { "Cu-63": 25, "Cu-65": 27 },
    ligands: [],
    coordinatedLigands: [{ ligand: "acac (acetylacetonate)", count: 2 }],
  },
  "VO(II)-acac2 in toluene (rhombic)": {
    metal: "Vanadium (V4+)",
    symmetry: "Rhombic",
    manualG: true,
    gx: 1.985,
    gy: 1.980,
    gz: 1.950,
    A_par: { "V-51": 170 },
    A_perp: { "V-51": 60 },
    ligands: [],
    coordinatedLigands: [{ ligand: "acac (acetylacetonate)", count: 2 }],
    distant_nuclei: [["H-1 (Protium)", 6, 7.0, 4.5]],
  },
  "Cu(II)-salen (rhombic, D2h)": {
    metal: "Copper (Cu2+)",
    symmetry: "Rhombic",
    manualG: true,
    gx: 2.035,
    gy: 2.055,
    gz: 2.200,
    A_par: { "Cu-63": 190, "Cu-65": 203 },
    A_perp: { "Cu-63": 30, "Cu-65": 32 },
    ligands: [{ isotope: "N-14", n: 2, A_par: 18.0, A_perp: 14.0 }],
    coordinatedLigands: [{ ligand: "salen", count: 1 }],
  },
  "Fe(III)-TPP bis-imidazole (rhombic, LS)": {
    metal: "Iron (Fe3+)",
    symmetry: "Rhombic",
    manualG: true,
    gx: 1.50,
    gy: 2.25,
    gz: 2.90,
    A_par: { "Fe-57": 22 },
    A_perp: { "Fe-57": 22 },
    ligands: [{ isotope: "N-14", n: 6, A_par: 8.0, A_perp: 6.0 }],
    coordinatedLigands: [{ ligand: "porphyrin (TPP)", count: 1 }, { ligand: "Imidazole (imH)", count: 2 }],
  },
};

export const presetKeys: string[] = Object.keys(presetDatabase);

