import { Preset } from './types';

export const presetDatabase: Record<string, Preset> = {
  "Cu(II)-tetraammine [Cu(NH3)4]2+ (D4h)": {
    metal: "Copper (Cu2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, elongated octahedral (D4h)",
    A_par: { "Cu-63": 200, "Cu-65": 214 },
    A_perp: { "Cu-63": 25, "Cu-65": 27 },
    ligands: [{ isotope: "N-14", n: 4, A_par: 15.0, A_perp: 15.0 }],
    distant_nuclei: [["H-1 (Protium)", 12, 8.0, 5.0]],
  },
  "Cu(II)-water [Cu(H2O)6]2+ (D4h)": {
    metal: "Copper (Cu2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, elongated octahedral (D4h)",
    A_par: { "Cu-63": 140, "Cu-65": 150 },
    A_perp: { "Cu-63": 20, "Cu-65": 21 },
    ligands: [],
    distant_nuclei: [["H-1 (Protium)", 12, 8.0, 5.0]],
  },
  "Mn(II)-water [Mn(H2O)6]2+ (Oh)": {
    metal: "Manganese (Mn2+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Mn-55": 90 },
    A_perp: { "Mn-55": 90 },
    ligands: [],
    distant_nuclei: [["H-1 (Protium)", 12, 8.0, 5.0]],
  },
  "VO(II)-water [VO(H2O)5]2+ (C4v)": {
    metal: "Vanadium (V4+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, square pyramidal (C4v)",
    A_par: { "V-51": 500 },
    A_perp: { "V-51": 170 },
    ligands: [],
    distant_nuclei: [["H-1 (Protium)", 10, 8.0, 5.0]],
  },
  "Cu(II)-acac2 [Cu(acac)2] (D2h)": {
    metal: "Copper (Cu2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, elongated octahedral (D4h)",
    A_par: { "Cu-63": 160, "Cu-65": 171 },
    A_perp: { "Cu-63": 25, "Cu-65": 27 },
    ligands: [],
    distant_nuclei: [["H-1 (Protium)", 6, 8.0, 5.0]],
  },
  "Cu(II)-en2 [Cu(en)2]2+ (D4h)": {
    metal: "Copper (Cu2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, elongated octahedral (D4h)",
    A_par: { "Cu-63": 190, "Cu-65": 203 },
    A_perp: { "Cu-63": 30, "Cu-65": 32 },
    ligands: [{ isotope: "N-14", n: 4, A_par: 25.0, A_perp: 20.0 }],
    distant_nuclei: [["H-1 (Protium)", 8, 10.0, 7.0]],
  },
  "Cu(II)-bipy2 [Cu(bipy)2]2+ (D2)": {
    metal: "Copper (Cu2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, elongated octahedral (D4h)",
    A_par: { "Cu-63": 170, "Cu-65": 182 },
    A_perp: { "Cu-63": 25, "Cu-65": 27 },
    ligands: [{ isotope: "N-14", n: 4, A_par: 15.0, A_perp: 12.0 }],
    distant_nuclei: [["H-1 (Protium)", 16, 5.0, 3.5]],
  },
  "VO(II)-acac2 [VO(acac)2] (C4v)": {
    metal: "Vanadium (V4+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, square pyramidal (C4v)",
    A_par: { "V-51": 500 },
    A_perp: { "V-51": 170 },
    ligands: [],
    distant_nuclei: [["H-1 (Protium)", 6, 7.0, 4.5]],
  },
  "Cr(III)-acac3 [Cr(acac)3] (D3)": {
    metal: "Chromium (Cr3+/Cr5+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Cr-53": 20 },
    A_perp: { "Cr-53": 20 },
    ligands: [],
    distant_nuclei: [["H-1 (Protium)", 9, 5.0, 3.5]],
  },
  "Au(II)-chloride [AuCl4]2- (D4h)": {
    metal: "Gold (Au2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, square planar (D4h)",
    A_par: { "Au-197": 60 },
    A_perp: { "Au-197": 25 },
    ligands: [{ isotope: "Cl-35", n: 4, A_par: 12.0, A_perp: 8.0 }],
  },
  "Au(II)-doped K2PtCl6 (Oh)": {
    metal: "Gold (Au2+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Au-197": 35 },
    A_perp: { "Au-197": 35 },
    ligands: [],
  },
  "Ag(II)-doped NaCl (Oh)": {
    metal: "Silver (Ag2+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Ag-107": 40, "Ag-109": 46 },
    A_perp: { "Ag-107": 40, "Ag-109": 46 },
    ligands: [],
  },
  "Ag(II)-water [Ag(H2O)6]2+ (D4h)": {
    metal: "Silver (Ag2+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, elongated octahedral (D4h)",
    A_par: { "Ag-107": 45, "Ag-109": 52 },
    A_perp: { "Ag-107": 12, "Ag-109": 14 },
    ligands: [{ isotope: "O-17", n: 6, A_par: 8.0, A_perp: 5.0 }],
    distant_nuclei: [["H-1 (Protium)", 12, 8.0, 5.0]],
  },
  "Pt(III)-chloride [PtCl6]3- (Oh)": {
    metal: "Platinum (Pt3+)",
    symmetry: "Cubic / isotropic",
    A_par: { "Pt-195": 80 },
    A_perp: { "Pt-195": 80 },
    ligands: [],
  },
  "Ni(I)-cyanide [Ni(CN)4]3- (D4h)": {
    metal: "Nickel (Ni+)",
    symmetry: "Axial (D4h / C4v / D3h)",
    stato: "d_x2-y2, square planar (D4h)",
    A_par: { "Ni-61": 20 },
    A_perp: { "Ni-61": 10 },
    ligands: [],
  },
};

export const presetKeys: string[] = Object.keys(presetDatabase);

